use Erp

create table Usuarios (
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL UNIQUE,
SENHAHASH VARBINARY(64) NOT NULL,
PERFIL TINYINT NOT NULL ,
ATIVO BIT NOT NULL,
DATACRIACAO DATETIME2 NOT NULL
);