use Erp

create table Usuarios (
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
EMPRESAID INT NOT NULL,
NOME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL UNIQUE,
SENHAHASH VARBINARY(64) NOT NULL,
PERFIL TINYINT NOT NULL ,
ATIVO BIT NOT NULL,
DATACRIACAO DATETIME2 NOT NULL

CONSTRAINT UQ_USUARIOS_EMPRESA_EMAIL
	UNIQUE(EMPRESAID, EMAIL)
);

INSERT INTO Usuarios (NOME, EMAIL, SENHAHASH, PERFIL, ATIVO, DATACRIACAO)
VALUES
('Maria Oliveira', 'joao@erpweb.com',
 HASHBYTES('SHA2_256', 'Joao@123'),
 2, 1, SYSDATETIME())

 select * from Usuarios


CREATE TABLE Empresas (
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NOMEFANTASIA VARCHAR (100) NOT NULL,
RAZAOSOCIAL VARCHAR (100) UNIQUE NOT NULL,
CNPJ CHAR (15) UNIQUE NOT NULL,
EMAIL VARCHAR (50) NOT NULL,
TELEFONE NVARCHAR (20) NOT NULL,
ATIVO BIT NOT NULL,
DATACRIACAO DATETIME2 NOT NULL 



 )

 